### ISSUE TITLE
consider deprecating this package

### ISSUE THREAD

**Issue by capaj** [jprichardson/atom-javascript-standard-snippets#1]
Comparing this with https://github.com/gaboesquivel/atom-standardjs-snippets it seems to me that it is much better for anyone to choose the other package, because it offers much more templates.
It is really a shame that google indexes this package much higher than the one from gaboesquivel.

**Comment by jprichardson** [comment]
> consider deprecating this package

Absolutely not. 

>  it seems to me that it is much better for anyone to choose the other package, because it offers much more templates.

More does not equate to better. I'm trying to find the right balance. Once you add a snippet, it'd be hard to change it because people will depend upon its existence. I made this mistake with https://github.com/jprichardson/sublime-js-snippets. 

> It is really a shame that google indexes this package much higher than the one from gaboesquivel.

Here's an idea. Instead of complaining, you could be proactive in two ways:
1. Use the package by gaboesquivel and encourage others to use it and Google indexing should follow.
2. Contribute ideas / snippets to this package so that it gets better.
3. Create your own.

Complaining is not a constructive way to achieve what you want.

**Comment by capaj** [comment]
I was not complaining. It was just a suggestion. It is okay if you don't feel the same way. This is your project, you can do as you like.

> More does not equate to better. 

In this case, it does.

> I'm trying to find the right balance. 

No you don't you just published 13 snippets and called it a day.

Again I am not complaining, I am grateful that you published this package. The stronger the Atom ecosystem is, the better. But like you said, 

> More does not equate to better. 

Which in the case of multiple Atom packages is true.
